# This file was generated by GoReleaser. DO NOT EDIT.
cask "aileron" do
  version "0.0.23"

  on_macos do
    on_intel do
      sha256 "ab9d712cb99e711516b493c81586a8ed1b9d2e576848b16d1d47368e349e873a"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c086050368e954dacd970a8c7e6d29c90455014c3dc147923bde19624881cb38"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63183e5c3807f31e2a5a85e429203e5557b3e9247f60f92e4aa83e7e920de308"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "26f2928aa0325c789094f0bd5f440fee5eb6610fe5a38289c43dba1a6fa80cda"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aileron"
  desc "Local LLM gateway for AI agents to take consequential action without holding credentials"
  homepage "https://withaileron.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aileron"
  binary "aileron-server"
  binary "aileron-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
