# This file was generated by GoReleaser. DO NOT EDIT.
cask "aileron" do
  version "0.0.26"

  on_macos do
    on_intel do
      sha256 "b7649b73c47ce0c54ff01f872a43c3d0b4de843f28ba711c162073a3e0f164fe"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea1f35ad4056ed0ae13dbcf3e9777a4732ea6e01069c446e9d36395972a574e5"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9910265116484a2194d1804bbf1ed3f7f74b7ac6b3b8a5485e1e6c3b6e28d690"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7f9032626d826070547d3efb533354ad5731be007d68d426fcfc06a5b962579"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aileron"
  desc "Local LLM gateway for AI agents to take consequential action without holding credentials"
  homepage "https://withaileron.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aileron"
  binary "aileron-server"
  binary "aileron-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
