# This file was generated by GoReleaser. DO NOT EDIT.
cask "aileron" do
  version "0.0.27"

  on_macos do
    on_intel do
      sha256 "553416393cbcba3c3ebb719cfbaaacd9b63d8b7572307bfe163aad4fa6f8f137"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab10d453f692d898e47d9d876c5465e1c0eba32dcffe8805415c5c01bce83df2"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "075809058538aa19e0432be9d9e30c04be6b2b82b0a9c1f5fd8606675c389acc"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fcf8278b286da2a7b9fe3f247692ce6bff351f772e705af1368e8dfa2eb534e"
      url "https://github.com/ALRubinger/aileron/releases/download/v#{version}/aileron_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aileron"
  desc "Local LLM gateway for AI agents to take consequential action without holding credentials"
  homepage "https://withaileron.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aileron"
  binary "aileron-server"
  binary "aileron-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
